theme: jekyll-theme-minimal
title: 'Fall single cell RNA sequencing workshop @ UCSF'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: welcome
  - title: What is Bioinformatics/Genomics Perspective?
    url: pdfs/Genomics_a_perspective_Sept2_2019.pdf
  - title: Experimental Design and Cost Estimation
    url: pdfs/singlecellRNAseq-expDesign.pdf

  - heading: Introduction to Command-Line and the Cluster
  - title: Logging in and Transferring Files
    url: cli/logging-in
  - title: Intro to Command-Line
    url: cli/command-line-intro
  - title: Advanced Command-Line (extra)
    url: cli/advanced-command-line
  - title: Running jobs on the Cluster and using modules
    url: cli/cluster

  - heading: Intro to R and Rstudio
  - title: Getting Started
    url: intro2R/RStudio
  - title: Intro to R
    url: intro2R/Intro2R_fixed
  - title: Prepare Data in R (extra)
    url: intro2R/data_in_R_prepare_fixed
  - title: Data in R (extra)
    url: intro2R/data_in_R_fixed

  - heading: Data Reduction
  - title: Project setup
    url: data_reduction/project_setup
  - title: Generating Expression Matrix
    url: data_reduction/Expression_Matrix

  - heading: scRNAseq Analysis
  - title: Prepare scRNAseq Analysis
    url: scrnaseq_analysis/scrna_analysis_prepare
  - title: scRNAseq Analysis - PART1
    url: scrnaseq_analysis/scRNA_Workshop-PART1_fixed
  - title: scRNAseq Analysis - PART2
    url: scrnaseq_analysis/scRNA_Workshop-PART2_fixed
  - title: scRNAseq Analysis - PART3
    url: scrnaseq_analysis/scRNA_Workshop-PART3_fixed
  - title: scRNAseq Analysis - PART4
    url: scrnaseq_analysis/scRNA_Workshop-PART4_fixed
  - title: scRNAseq Analysis - PART5
    url: scrnaseq_analysis/scRNA_Workshop-PART5_fixed
  - title: scRNAseq Analysis - PART6
    url: scrnaseq_analysis/scRNA_Workshop-PART6_fixed

  - heading: Guest lecture by Dr. Gerald Quon
  - title: Prepare Single Cell Alignment
    url: scrnaseq_analysis/scrna_analysis_prepare-alignment
  - title: Single Cell Alignment (scAlign)
    url: scrnaseq_analysis/scRNA_Workshop-alignment_fixed

  - heading: Support
  - title: Cheat Sheets
    url: cheatSheetIndex
  - title: Software and Links
    url: software
  - title: Scripts
    url: scripts_links

  - heading: ETC
  - title: Closing thoughts
    url: closing
  - title: Workshop Photos
    url: photos/photos
  - title: Github
    url: https://github.com/ucdavis-bioinformatics-training/2019-Fall-single-cell-RNA-sequencing-Workshop-UCSF
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
